name: Code Review with ChatGPT

permissions:
  contents: read
  pull-requests: write

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Review with ChatGPT
        uses: anc95/ChatGPT-CodeReview@main
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}

